=== khangtran123/4850Lab8/data/classSchedule.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
        This is the core structure of our winter 2016 
        timetable. A semester can have as many days elements, each days element 
        contains a timeslot and each timeslot can have one course. 
-->


<!-- The root element contains a week element, and then multiple source elements,
each of which models data from a specific course.
 -->
<!ELEMENT schedule (courses|days|timeslots)*>

<!-- Element Booking is used in all 3 facets. -->
<!ELEMENT booking EMPTY>
<!ATTLIST booking
    courseID (4620|4650|4660|4770|4850|4910) #IMPLIED
    weekDay (Monday|Tuesday|Wednesday|Thursday|Friday) #IMPLIED
    startTime (8:30|9:30|10:30|11:30|12:30|1:30|2:30|3:30|4:30) #IMPLIED
    endTime CDATA #REQUIRED
    instructor CDATA #REQUIRED
    classActivity (Lecture|Tutorial|Lab) #REQUIRED
    classLocation CDATA #REQUIRED
>

<!-- Root courses element for courses facet.-->  
<!ELEMENT courses (course)*>
<!--- Element course contains course and its data. -->
<!ELEMENT course (booking)*>
<!ATTLIST course
    courseID (4620|4650|4660|4770|4850|4910) #REQUIRED
>

<!--- Root element for days facet. -->
<!ELEMENT days (day)*>

<!--- Day element for days of the week. -->
<!ELEMENT day (booking)*>
<!ATTLIST day
    weekDay (Monday|Tuesday|Wednesday|Thursday|Friday) #REQUIRED
>

<!-- The timeslots element contains all the course timeslots of the week -->
<!ELEMENT timeslots (timeslot)*>
<!ELEMENT timeslot (booking)*>
<!ATTLIST timeslot 
    startTime (8:30|9:30|10:30|11:30|12:30|1:30|2:30|3:30|4:30) #REQUIRED
>

=== khangtran123/4850Lab8/data/timeslot_facet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timeslots SYSTEM "classSchedule.dtd">



<timeslots>
    <timeslot time="8:30">
        <booking day="Friday" startTime="8:30" endTime="10:20" instructor="Steve" classActivity="Lecture" classLocation="SW9-206" />
    </timeslot>
    <timeslot time="9:30">
        <booking day="Thursday" startTime="9:30" endTime="10:20" instructor="Richard" classActivity="Lecture" classLocation="SW5-1840" />
    </timeslot>
    <timeslot time="10:30">
        <booking day="Tuesday" startTime="10:30" endTime="12:20" instructor="Bethany" classActivity="Lab" classLocation="SE12-306" />
        <booking day="Wednesday" startTime="10:30" endTime="12:20" instructor="Steve" classActivity="Lab" classLocation="SE12-306" />
        <booking day="Thursday" startTime="10:30" endTime="12:20" instructor="Jim" classActivity="Lab" classLocation="SE12-320" />
    </timeslot>
    <timeslot time="11:30">
        <booking day="Tuesday" startTime="12:30" endTime="1:20" instructor="Medhat" classActivity="Lecture" classLocation="SW9-206" />
        <booking day="Wednesday" startTime="12:30" endTime="2:20" instructor="Jim" classActivity="Lecture" classLocation="SW3-1750" />
    </timeslot>
    <timeslot time="1:30">
        <booking day="Monday" startTime="1:30" endTime="3:20" instructor="Trevor" classActivity="Tutorial" classLocation="SE12-306" />
        <booking day="Tuesday" startTime="1:30" endTime="3:20" instructor="Medhat" classActivity="Lab" classLocation="SE12-306" />
        <booking day="Thursday" startTime="1:30" endTime="3:20" instructor="Richard" classActivity="Lab" classLocation="SE12-306" />
    </timeslot>
    <timeslot time="3:30">
        <booking day="Monday" startTime="3:30" endTime="4:20" instructor="Richard" classActivity="Lecture" classLocation="SW9-206" />
        <booking day="Tuesday" startTime="3:30" endTime="5:20" instructor="Bethany" classActivity="Lecture" classLocation="SW3-3615" />
    </timeslot>
    <timeslot time="4:30">
        <booking day="Monday" startTime="4:30" endTime="5:20" instructor="Medhat" classActivity="Lecture" classLocation="SE6-205" />
    </timeslot>
            
</timeslots>

=== khangtran123/4850Lab8/data/master.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schedule SYSTEM "classSchedule.dtd">


<!-- This is the facet structure for all the courses we want displayed -->
<schedule>
    <courses>
        <course courseID="4620">
            <booking courseName="4620" weekDay="Tuesday" startTime="10:30" endTime="12:20" instructor="Bethany" classActivity="Lab" classLocation="SE12-306" />
            <booking courseName="4620" weekDay="Tuesday" startTime="3:30" endTime="5:20" instructor="Bethany" classActivity="Lecture" classLocation="SW3-3615" />
        </course>
        <course courseID="4650">
            <booking courseName="4650" weekDay="Monday" startTime="4:30" endTime="5:20" instructor="Medhat" classActivity="Lecture" classLocation="SE6-205" />
            <booking courseName="4650" weekDay="Tuesday" startTime="12:30" endTime="1:20" instructor="Medhat" classActivity="Lecture" classLocation="SW9-206" />
            <booking courseName="4650" weekDay="Tuesday" startTime="1:30" endTime="3:20" instructor="Medhat" classActivity="Lab" classLocation="SE12-306" />
        </course>
        <course courseID="4660">
            <booking courseName="4660" weekDay="Wednesday" startTime="10:30" endTime="12:20" instructor="Steve" classActivity="Lab" classLocation="SE12-306" />
            <booking courseName="4660" weekDay="Friday" startTime="8:30" endTime="10:20" instructor="Steve" classActivity="Lecture" classLocation="SW9-206" />
        </course>
        <course courseID="4770">
            <booking courseName="4770" weekDay="Monday" startTime="1:30" endTime="3:20" instructor="Trevor" classActivity="Tutorial" classLocation="SE12-306" />
        </course>
        <course courseID="4850">
            <booking courseName="4850" weekDay="Wednesday" startTime="12:30" endTime="2:20" instructor="Jim" classActivity="Lecture" classLocation="SW3-1750" />
            <booking courseName="4850" weekDay="Thursday" startTime="10:30" endTime="12:20" instructor="Jim" classActivity="Lab" classLocation="SE12-320" />
        </course>
        <course courseID="4910">
            <booking courseName="4910" weekDay="Monday" startTime="3:30" endTime="4:20" instructor="Richard" classActivity="Lecture" classLocation="SW9-206" />
            <booking courseName="4910" weekDay="Thursday" startTime="9:30" endTime="10:20" instructor="Richard" classActivity="Lecture" classLocation="SW5-1840" />
            <booking courseName="4910" weekDay="Thursday" startTime="1:30" endTime="3:20" instructor="Richard" classActivity="Lab" classLocation="SE12-306" />
        </course>
    </courses>

    <days>
        <day daySchedule="Monday">
            <booking courseName="4770" weekDay="Monday" startTime="1:30" endTime="3:20" instructor="Trevor" classActivity="Tutorial" classLocation="SE12-306" />
            <booking courseName="4910" weekDay="Monday" startTime="3:30" endTime="4:20" instructor="Richard" classActivity="Lecture" classLocation="SW9-206" />
            <booking courseName="4650" weekDay="Monday" startTime="4:30" endTime="5:20" instructor="Medhat" classActivity="Lecture" classLocation="SE6-205" />
        </day>
        <day daySchedule="Tuesday">
            <booking courseName="4620" weekDay="Tuesday" startTime="10:30" endTime="12:20" instructor="Bethany" classActivity="Lab" classLocation="SE12-306" />
            <booking courseName="4650" weekDay="Tuesday" startTime="12:30" endTime="1:20" instructor="Medhat" classActivity="Lecture" classLocation="SW9-206" />
            <booking courseName="4650" weekDay="Tuesday" startTime="1:30" endTime="3:20" instructor="Medhat" classActivity="Lab" classLocation="SE12-306" />
            <booking courseName="4620" weekDay="Tuesday" startTime="3:30" endTime="5:20" instructor="Bethany" classActivity="Lecture" classLocation="SW3-3615" />
        </day>
        <day daySchedule="Wednesday">
            <booking courseName="4660" weekDay="Wednesday" startTime="10:30" endTime="12:20" instructor="Steve" classActivity="Lab" classLocation="SE12-306" />
            <booking courseName="4850" weekDay="Wednesday" startTime="12:30" endTime="2:20" instructor="Jim" classActivity="Lecture" classLocation="SW3-1750" />
        </day>
        <day daySchedule="Thursday">
            <booking courseName="4910" weekDay="Thursday" startTime="9:30" endTime="10:20" instructor="Richard" classActivity="Lecture" classLocation="SW5-1840" />
            <booking courseName="4850" weekDay="Thursday" startTime="10:30" endTime="12:20" instructor="Jim" classActivity="Lab" classLocation="SE12-320" />
            <booking courseName="4910" weekDay="Thursday" startTime="1:30" endTime="3:20" instructor="Richard" classActivity="Lab" classLocation="SE12-306" />
        </day>
        <day daySchedule="Friday">
            <booking courseName="4660" weekDay="Friday" startTime="8:30" endTime="10:20" instructor="Steve" classActivity="Lecture" classLocation="SW9-206" />
        </day>
    </days>

    <timeslots>
        <timeslot time="8:30">
            <booking courseName="4660" weekDay="Friday" startTime="8:30" endTime="10:20" instructor="Steve" classActivity="Lecture" classLocation="SW9-206" />
        </timeslot>
        <timeslot time="9:30">
            <booking courseName="4910" weekDay="Thursday" startTime="9:30" endTime="10:20" instructor="Richard" classActivity="Lecture" classLocation="SW5-1840" />
        </timeslot>
        <timeslot time="10:30">
            <booking courseName="4620" weekDay="Tuesday" startTime="10:30" endTime="12:20" instructor="Bethany" classActivity="Lab" classLocation="SE12-306" />
            <booking courseName="4660" weekDay="Wednesday" startTime="10:30" endTime="12:20" instructor="Steve" classActivity="Lab" classLocation="SE12-306" />
            <booking courseName="4850" weekDay="Thursday" startTime="10:30" endTime="12:20" instructor="Jim" classActivity="Lab" classLocation="SE12-320" />
        </timeslot>
        <timeslot time="11:30">
            <booking courseName="4650" weekDay="Tuesday" startTime="12:30" endTime="1:20" instructor="Medhat" classActivity="Lecture" classLocation="SW9-206" />
            <booking courseName="4850" weekDay="Wednesday" startTime="12:30" endTime="2:20" instructor="Jim" classActivity="Lecture" classLocation="SW3-1750" />
        </timeslot>
        <timeslot time="1:30">
            <booking courseName="4770" weekDay="Monday" startTime="1:30" endTime="3:20" instructor="Trevor" classActivity="Tutorial" classLocation="SE12-306" />
            <booking courseName="4650" weekDay="Tuesday" startTime="1:30" endTime="3:20" instructor="Medhat" classActivity="Lab" classLocation="SE12-306" />
            <booking courseName="4910" weekDay="Thursday" startTime="1:30" endTime="3:20" instructor="Richard" classActivity="Lab" classLocation="SE12-306" />
        </timeslot>
        <timeslot time="3:30">
            <booking courseName="4910" weekDay="Monday" startTime="3:30" endTime="4:20" instructor="Richard" classActivity="Lecture" classLocation="SW9-206" />
            <booking courseName="4620" weekDay="Tuesday" startTime="3:30" endTime="5:20" instructor="Bethany" classActivity="Lecture" classLocation="SW3-3615" />
        </timeslot>
        <timeslot time="4:30">
            <booking courseName="4650" weekDay="Monday" startTime="4:30" endTime="5:20" instructor="Medhat" classActivity="Lecture" classLocation="SE6-205" />
        </timeslot>
            
    </timeslots>
</schedule>
